### ISSUE TITLE
OpenCV Error

### ISSUE THREAD

**Issue by liabixiaoxin** [jaredraycoleman/lane_detection#1]
Hi,
I was trying to run your demo code recently. When I run the executable from project home directory, it pops up an error like this: 

"OpenCV Error: Gpu API call (invalid argument) in bindTexture, file /home/nvidia/opencv/modules/core/include/opencv2/core/cuda/common.hpp, line 102
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/nvidia/opencv/modules/core/include/opencv2/core/cuda/common.hpp:102: error: (-217) invalid argument in function bindTexture

Aborted (core dumped)"

I'm using TX2 with OpenCV 3.3.0 & CUDA-9.0. In your detect.cu, I changed the including line "gpu/gpu.hpp" to "core/cuda.hpp" when compiling since I guess that's for the OpenCV 2.4.x version. Not sure if you have tested the project based on the latest OpenCV version.

**Comment by jaredraycoleman** [comment]
Hello liabixiaoxin, Sorry for the slow response. I have only tested for OpenCV 2.4.x, which comes with Jetpack, last time I flashed.
