### ISSUE TITLE
Could you explain the detect.cfg ?

### ISSUE THREAD

**Issue by zacario-li** [jaredraycoleman/lane_detection#3]
Hi, I'm testing this on my TX2 with my own video.
I modified some configs in 'detect.cfg', I don't know what does "camera.height/angle" mean. Why the camera.height set to "0.2/0.239" in your config file? If I want to change it , which value should I set?

**Comment by jaredraycoleman** [comment]
Hey @zacario-li, this code is for a research project and isn't always up-to-date or organized. Some of the values specified in config files aren't being used. The "camera.height/angle" isn't being used currently.
